### ISSUE TITLE
need xslt  for quality level mpd file as well.

### ISSUE THREAD

**Issue by aamir2007** [squidpickles/mpd-to-m3u8#2]
Its a great idea to build m3u8 from mpd using xslt file however your file only converts master file and asks to manually build child/quality level files.
However I would like to build quality level file as well using this technique as Now apple HLS now supports fragmented mp4 files. See below article for reference.
https://www.streamingmedia.com/Articles/News/Online-Video-News/HLS-Now-Supports-Fragmented-MP4-Making-it-Compatible-With-DASH-111796.aspx

**Comment by squidpickles** [comment]
Do you have an example MPD file that you would like to convert? I'd be happy to have a look, though I'm not doing any work in this space these days, so anything too complex may take a while to get to.

**Comment by ghost** [comment]
@squidpickles squidpickles
Hi, I hope you are well. I used your technique but I still can't. I just wanted to convert this link. Could you help me please ? Thank you

http://a3m-mega-vod-dash.secure.footprint.net/live/nas_live/mega/dash/mega.mpd?begin=&end=&nvb=1527155886&nva=1958691886&hash=0b2c7333d5b73ad0d557858226387777

It works since July

**Comment by squidpickles** [comment]
Hi @ZaidCh100, that link returns a `403 Forbidden` error. Can you attach an actual example MPD?

**Comment by ZaidCh100** [comment]
@squidpickles 
The VLC player continues to work. I have another link, I don't know if you can convert it to m3u8. I'm so sorry, I'm new to all of that. Thank you very much for helping me.

https://rtlbe.live.6cloud.fr/out/u/rtl_be/rlt_tvi_sd_p.mpd

**Comment by ghost** [comment]
Hello @squidpickles , thank you very much for responding.
In the VLC player continues to work. I have another link, I don't know if you can convert it to m3u8. I'm so sorry, I'm new to all of that. Thank you very much for helping me.

https://rtlbe.live.6cloud.fr/out/u/rtl_be/rlt_tvi_sd_p.mpd

(Sorry for my English, I am learning.) 👍

**Comment by ghost** [comment]
@squidpickles 

I'm sorry, I just realized that it was not the good link. It was this:
http://a3m-mega-vod-dash.secure.footprint.net/live/nas_live/mega/dash/mega.mpd?begin=&end=&nvb=1527155886&nva=1958691886&hash=0b2c7333d5b73ad0d55785822992f7772763885bc

I had made a mistake. Thank you very much for helping.

**Comment by squidpickles** [comment]
I had another look based on the link you sent. I think it is a fairly big step to make this work, as there are several features (initialization segments, templates) that aren't supported in this project. 

The naming convention as well is different; this hardcodes `${run_id}_${representation_id}.mp4` as the name, whereas the URL you provided uses `mega-${representation_id}-${number}.m4s`. That's not too hard to change (it's built up here https://github.com/squidpickles/mpd-to-m3u8/blob/4c911a20d984dcb2a9910c223a203d6599f17968/mpd_to_hls.xsl#L32-L36), but I think it'd be a pretty long list of steps to make this work.

This project is mainly geared towards content creators, and pretty much only solves a single problem of generating HLS playlists with correct codec/bandwidth/resolutions listed in the headers, because at the time it was written, the HLS-generation tools didn't do a good job of that. It's likely there's something else out there that does this now.
